on:
  - pull_request

name: Test

jobs:
  lint:
    name: Lint the code
    runs-on: macos-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1
          working-directory: ./

  test:
    name: Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: download deps
        run: go get .

      - name: Test
        run: go test

  build-binary:
    name: Build multi-architecture binary
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: download deps
        run: go get .

      - name: Build
        run: ./build.sh
